### ISSUE TITLE
“unit_kilo” and "prefix_with_reset" really work?

### ISSUE THREAD

**Issue by jan-rex** [eza-community/eza#1293]
Hi,
I have tried using “unit_kilo” and “prefix_with_reset,” but they haven’t worked for me. Do they actually work? I am using macOS.

**Comment by PThorpe92** [comment]
`unit_kilo` does seem to work for me.
 
![image](https://github.com/user-attachments/assets/535962c5-3c9d-4d54-ae21-23c22fa6df84)

I'm not sure if `prefix_with_reset` is actually necessary, as the styles are applied to each individually and it's unlikely to need reset code, and would probably just cause more unneeded text output. I would only use it if you are getting a style applied that you are not expecting and want to clear it first.

**Comment by jan-rex** [comment]
What I want to do is be able to use unit_kilo and the other parameters, but it has no effect, so I thought using reset would enable its use, but it doesn’t have any effect either.

**Comment by jan-rex** [comment]
I’m not sure if I’ve misunderstood the purpose of unit_kilo and the others. I thought I understood that they were used to format how the units are displayed. Is that correct, or do they serve a different function?

**Comment by PThorpe92** [comment]
Yeah it's  you can see the difference in the photo if you look at the lower example, size values that are `kb`, are displayed in dark blue, where above they are off-white.

```yml
size:
  major: {foreground: "#A6ADC8"}
  minor: {foreground: "#89DCEB"}
  number_byte: {foreground: "#CDD6F4"}
  number_kilo: {foreground: "#000FFF"} #  the foreground value was changed to make that happen 
  number_mega: {foreground: "#89B4FA"}
``` 

This will affect any size that is displayed in kilobytes 
![image](https://github.com/user-attachments/assets/9a641245-5e4b-4f7e-b70f-25c15a7e3c36)
